version: "3.8"
services:
  transformer-api:
    image: teclead/t1-model:transformerV0.4.5
    ports:
      - "8080:8080"
    entrypoint:
      ["uvicorn", "api.transformer_v1:app", "--host", "0.0.0.0", "--port", "8080"]
    env_file:
      - ../../.env
    labels:
      kompose.image-pull-secret	: "tlv-docker"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 60s
      timeout: 2s
      retries: 5
      start_period: 10s


  trading-manager:
    image: teclead/t1-m7:transformerV0.4.6
    ports:
      - "7001:7001"
    env_file:
      - ../../.env
    labels:
      kompose.image-pull-secret	: "tlv-docker"
    environment:
      - portfolioIds=["intraday-spread-50MW", "intraday-spread-single-trade"]
      - t1ModelDomain=http://transformer-api:8080

    depends_on:
      - transformer-api
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7001 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

