apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes/
    kompose.image-pull-secret: tlv-docker
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: transformer-v1-tm
  name: transformer-v1-tm
spec:
  ports:
    - name: "7001"
      port: 7001
      targetPort: 7001
  selector:
    io.kompose.service: transformer-v1-tm
