apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes/
    kompose.image-pull-secret: tlv-docker
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: transformer-v1-api
  name: transformer-v1-api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: transformer-v1-api
